### ISSUE TITLE
Q: Where do you instantiate?

### ISSUE THREAD

**Issue by notflip** [lavary/laravel-menu#111]
Is there a place you generally instantiate the menu? Or an option which is best for performance? 
Thank you!

**Comment by zanematthew** [comment]
@notflip This may help? https://github.com/lavary/laravel-menu/issues/110
https://github.com/lavary/laravel-menu/wiki/Basics-of-Menus

Wondering the same, additionally whats best practice for having multiple menus?

**Comment by zanematthew** [comment]
@notflip Here's how I did mine...


1. Using artisan `$ php artisan make:middleware MenuMiddleware`
2. Added the following code `App\Http\Middleware\MenuMiddleware.php`
``` php
<?php

namespace App\Http\Middleware

use Closure;
use Menu;

class MenuMiddleware
{
    /**
     * Run the request filter.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure                  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        Menu::make('example', function($menu) {
            $menu->add('Home', '/');
            $menu->add('About', '/about');
            $menu->add('Blog', '/blog');
            $menu->add('Contact Me', '/contact-me');
        });

        Menu::make('exampleTwo', function($menu) {
            $menu->add('A', '/a');
            $menu->add('B', '/b');
            $menu->add('C', '/c');
        });

        return $next($request);
    }
}
```
3. Registered it in `App\Http\Kernal.php`, in the `$routeMiddleware` array `'menu' => \App\Http\Middleware\MenuMiddleware::class,`
4. Finally in my `routes.php` file
``` php
$router->group(['middleware' => ['auth', 'menu']], function ($router) {
     // some code
});
```

I'd love to know whats best for "performance", and what tools are used to measure "performance".

**Comment by notflip** [comment]
This seems like a very good implementation! Thank you for that. Im also
curious how different middleware layers affect performance.

**Comment by adam-boduch** [comment]
You can put in your base controller. Something like this:

```php
abstract class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;

    /**
     * Application menu. Menu can be overwrite in admin panel.
     *
     * @return \Lavary\Menu\Builder
     */
    protected function buildMenu()
    {
        $menu = app(Menu::class)->make('main', function ($menu) {
            // ...
        });

        return $menu;
    }

    /**
     * Renders view with breadcrumb
     *
     * @param string|null $view
     * @param array $data
     * @return \Illuminate\View\View
     */
    protected function view($view = null, $data = [])
    {
        if (!request()->ajax()) {
            $data['menu'] = $this->buildMenu();
        }

        return view($view, $data);
    }
}
```

**Comment by zanematthew** [comment]
Would a more "Laravel" way be to create a `directive` for the menu?

`{{ myMenu }}`

**Comment by VictorZZZZ** [comment]
It managed to me realize this through the Middleware, it's ok.

But i have a question.
I have a **CamaignsController extends Controller**.
I tryed to do this through the **__constructor** of CamaignsController And it managed.

`
public function __constructor(){
     Menu::make('MyNavBar', function($menu){

       $menu->add('Home');
       $menu->add('About',    'about');
       $menu->add('services', 'services');
       $menu->add('Contact',  'contact');

    });
}
`
And i have an access to the $MyNavBar variable in views of CamaignsController.

But when I add this code to the constructor of Controller class, I get an error.

Why couln't I add this code to **Controller** class? I thought that **CampaignsController** extends all methods of **Controller**

**Comment by dustingraham** [comment]
@VictorZZZZ Regarding the error, can you open a new issue with the error message if you still have a problem? You certainly should be able to init the menu in your Controller.

@zanematthew It is already pretty short at {!! $myMenu->asUl() !!} I don't think it needs to be shorter. Also, since you could have more than one menu, there isn't a default menu name that could be linked.

Regarding this discussion, I think it is really a case by case basis. All suggestions have merit depending on how simple or complex your menu is. A different constructor in each controller if your menu is controller specific could work in some cases. Middleware, or even named middleware would work in other cases. View composers could also work fairly well if you have the view composer attached to the view where your menu is rendered.

If anyone is experiencing any speed issues, please create an issue to let us know. One idea might be to not execute the menu callback until it's needed. But that would remove the convenience variables in the views.

**Comment by ultrono** [comment]
I used a View Composer, seems the neatest way imo :)

**Comment by dustingraham** [comment]
Closing as a non-issue. If there's an issue please open a new ticket. Reference this one if needed. :)
