### ISSUE TITLE
Add current username to navbar

### ISSUE THREAD

**Issue by ttimot24** [lavary/laravel-menu#146]
Hi!

I want to show the currently logged in users's username on bootstrap navbar.
I tried a lot of ways but I always get this error: "Trying to get property of non-object";

Is there any way to pass as an argument in render time or any other idea how can I solve this?

**Comment by xnetmexico** [comment]
Hi ttimot24 I created a pull request with a mod to allow this ,

I made an exaple on this post 
https://github.com/lavary/laravel-menu/issues/138

hth

Rodrigo O
Xnet

**Comment by dustingraham** [comment]
This might be best in a base controller, or a view composer. But you could add in your view as well at the top.

    $name = User::active()->first_name;
    \Menu::make('MyNavBar', function ($menu) use($name) {
        $menu->add('User: '.$name, 'profile/view');
    });

Which will add User: Name to the end of the MyNavBar navbar, which you may have declared earlier such as in the middleware. It would also work to just use...

    \Menu::make('MyNavBar', function ($menu) {
        $menu->add(User::active()->first_name, 'profile/view');
    });

Again, calling ::make() a second time will add on to the existing menu.

Since this is old, I'm going to close it. If you still need help please re-open.
