### ISSUE TITLE
how to use uff-8 

### ISSUE THREAD

**Issue by thandonguocmo2020** [lavary/laravel-menu#152]
why it not run ? help

 Menu::make('MyNavBar', function($menu){

            $menu->add('trang chủ', array('route'  => 'home.index'));
            $menu->item('trang chủ')->add('demo menu', 'demo menu');

        });

-----------------------------------------------------------------------------------------

it run  : 

  Menu::make('MyNavBar', function($menu){

            $menu->add('home', array('route'  => 'home.index'));
            $menu->item('home')->add('demo menu', 'trang con');

        });

**Comment by lavary** [comment]
Since any menu item is turned into Ascii code for creating nicknames, you item will turn into: `trang chu`.
Consequently, the nickname would be `trangChu`.

You can also save your menu item in a variable for reference - if you don't want to use the nicknames:

```php
<?php

// ...

$trangChu = $menu->add('trang chủ', array('route'  => 'home.index'));
$trangChue->add('demo menu', 'demo menu');

// ...

```

Hope the above helps.

-----
Closing the issue. Please feel free to reopen if you have any more questions regarding the encoding.

Thanks.
