### ISSUE TITLE
Show boxen in menu

### ISSUE THREAD

**Issue by Blackfire499** [lavary/laravel-menu#233]
Hi guys one question is it prossible to show Boxen like a Login Box or Statistic Box with laravel-menu??

if not would be nice to have a function like:

`$menu->makeBox('BoxName','boxController');`

this would include the needed Controller for the box and show it in the menu

**Comment by dustingraham** [comment]
Howdy. We don't have any functionality that would do exactly that. You can use $menu->raw('...'); but that seems like a lot of markup to fit in a single string. Might work for you though.

Otherwise, you'll need to look into the advanced features to see if any would apply to you.\

https://github.com/lavary/laravel-menu#advanced-usage

Such as the custom-menu-items and perhaps set a data value to something that would trigger a different if/else block to render. That's beyond the scope of what we can support via issues though.
