### ISSUE TITLE
Hidden parent menu

### ISSUE THREAD

**Issue by kufdaw** [lavary/laravel-menu#244]
Hey,

Now my menu working this way (nested): when some nested item is active - the item and its parent hover. But the parent menu is closed, I want it to be shown, like "dropdowned" already.

This is config of mine:
```
<?php

return array(
    'default' => array(
        'auto_activate' => true,
        'activate_parents' => true,
        'active_class' => 'active',
        'restful' => false,
        'cascade_data' => true,
        'rest_base' => '',      // string|array
        'active_element' => 'link',  // item|link
    ),
);

```

**Comment by dustingraham** [comment]
What have you tried? What problems have you encountered? Seems like you could use CSS to show/hide based on active state.

**Comment by bomkallo** [comment]
I feel like this menu is not built for fireworks, if you're bored, just rewrite gantry5 menus and JS scripts, ( i have adapted percentage grid system instead of lame 12-col bootstrap ) Though, this menu needs depth function and dynamic JS selection classes at least. Regarding the css above, you can't do it without JS, so your answer fails badly. 

Anyway, menu systems and routing are the most complicated parts of all frameworks, so you're asking a big deal of trouble :)
