### ISSUE TITLE
Auto-activated links with anchor

### ISSUE THREAD

**Issue by cugrif** [lavary/laravel-menu#248]
Hi
Thanks for your good extension.

I trying to set-up behavior of my menu and i have some trouble.

Menu:
* **Home**      href="/"
* **Fruits**       href="#"
  *  **Apples**   href="/apples"

Config
```php
return array(
    'default' => array(
        'auto_activate' => true,
        'activate_parents' => true,
        'active_class' => 'active',
        'restful' => true,
        'cascade_data' => true,
        'rest_base' => '',     
        'active_element' => 'item', 
    ),
);
```

The fruits is not clickable item. It's a folder.
I want :
1. When i m on page Home, then the Home is active only
2. When i m on page Apples, then it's active
3. When i m on route /apples/create (not present in menu), then Apples is active.

I set restful = true in config for resolve №3
But when I on Home page, then all menu items with link "#" are active. (example: Fruits)

Any idea?
Best regards

**Comment by dustingraham** [comment]
I think that is expected since a hash `#` is the same as `/` with regards to path and auto-activation.

You could try creating some code to manually activate based your your logic.

Another option you might try is using a `->raw(...)` element, but I don't remember if `raw` works with children. I took a quick look at the code and it might. Sorry I don't have time to test it further presently.

**Comment by dustingraham** [comment]
Resolved with 249.
