### ISSUE TITLE
descendants with relationship

### ISSUE THREAD

**Issue by Vmadmax** [lavary/laravel-menu#262]
Hi, 
is there a way to get the descendants of a current link with relations?

```php
$root_elements = SiteMenuEntries::with('abc')->withDepth()->having('depth', '=', 0)->with('descendants')->orderBy('order', 'ASC')->get();

foreach ($root_elements as $link) {
    $descendants = $link->descendants; // Here I need to have the relations "with('abc')"
}
```

**Comment by dustingraham** [comment]
I'm not sure I follow.

`with(...)` is not a laravel menu function.

**Comment by Vmadmax** [comment]
Correct. I’m building  the menu throught database entries.

**Comment by dustingraham** [comment]
Ok, so you'll need to explain your question a little more if this doesn't help.

You can use `$menu->get('abc')` to get that item.
- https://github.com/lavary/laravel-menu#sub-items

Since you're using a database, you might even consider setting the ID items manually so you can pull up any ID you want. It also allows you to specifically set the parent ID. (All of this is mentioned near that sub-items link I included.)
