### ISSUE TITLE
Sub Menu - CSS Class

### ISSUE THREAD

**Issue by jaiimg** [lavary/laravel-menu#48]
I need a set class for sub menu ul

~~~
<ul>
    <li  class="navbar navbar-home" id="home"><a href="/">Home</a></li>
    <li  data-role="navigation" class="navbar navbar-about dropdown"><a href="#">About</a>
        
     // Need to set <ul class='submenu'>
    <ul> 
           <li><a href="#>Who we are?</a></li>
           <li><a href="#">What we do?</a></li>
     </ul>
    </li>

    <li><a href="services">Services</a></li>
    <li><a href="contact">Contact</a></li>
</ul>
~~~

**Comment by jaiimg** [comment]
my theme need this class <ul class='submenu'> to be submenu, how can i do that

**Comment by jaiimg** [comment]
Hi, i did it with chaging onload with Jquery
http://api.jquery.com/addclass/

if possible, Kindly include such option on next updates

**Comment by fredrkr** [comment]
This issue should not be closed. There are most definitely use-cases where you'd need to specify a class for a submenu-element, not only because of css, but also javascript.

I'm using a theme that runs a javascript on DOM ready function to configure the whole template, including submenus. Also, the theme's less-files uses the same submenu class as the javascript.

Instead of having to change the theme's sourcecode, I'd much rather specify a class with this, otherwise, awesome package. I guess the only option is writing a custom view.

**Comment by nasirkhan** [comment]
I need the solution for this. could not find any doc related submenu ul class. @piperone  did you find the solution?
